### ISSUE TITLE
Configure karaf to store its tmp and bundle cache outside of the data dir

### ISSUE THREAD

**Issue by chirino** [jboss-fuse/jboss-fuse-docker#2]
That way when a new docker instance starts up against an existing data volume, it picks up any bundle updates in the base image.

**Comment by gnodet** [comment]
The osgi cache is controlled using the org.osgi.framework.storage property which can be set in etc/config.properties.  If not set, it defaults to ${kara.data}/cache.

The temp dir is configured in the shell scripts that launch the JVM using -Djava.io.tmpdir="$KARAF_DATA/tmp".
