### ISSUE TITLE
${HOME} in Dockerfile is empty

### ISSUE THREAD

**Issue by jsedlace** [jboss-fuse/jboss-fuse-docker#5]
the image doesn't start with default CMD:
/bin/sh: //jboss-fuse/bin/fuse: No such file or directory

I looked into the image using /bin/bash, $HOME variable is set to /.

**Comment by chirino** [comment]
Well I'm not sure why $HOME is not set for you.  But I'f pushed a change to make the CMD not depend on the $HOME variable.
